#!/usr/bin/env node

/**
 * Generate Game Script
 * Creates a personalized game for a pet by injecting config into the template.
 *
 * Usage:
 *   node scripts/generate-game.js <petName>
 *   node scripts/generate-game.js <petName> --config <configPath>
 *
 * Examples:
 *   node scripts/generate-game.js bowie
 *   node scripts/generate-game.js fluffy --config configs/fluffy.json
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT_DIR = path.resolve(__dirname, '..')

// Default config template - used when no config file is provided
function createDefaultConfig(petName) {
  const displayName = petName.charAt(0).toUpperCase() + petName.slice(1).toLowerCase()
  return {
    petName: petName.toLowerCase(),
    petDisplayName: displayName,
    sprites: {
      cat: `../sprites/${petName.toLowerCase()}/${petName.toLowerCase()}_cat_3x3.png`,
      foodBowl: '../sprites/shared/pet_food_bowl.png',
      waterBowl: '../sprites/shared/pet_water_bowl.png',
      dog: '../sprites/shared/bonbon_dog_3x3.png',
      catTree: '../sprites/shared/cat-tree.png'
    },
    gameTitle: `${displayName}'s Adventure`,
    primaryColor: '#e94560'
  }
}

// Generate the config script block that replaces the placeholder
function generateConfigScript(config) {
  return `// GAME_CONFIG - Generated for ${config.petDisplayName}
    // Generated by generate-game.js
    const GAME_CONFIG = ${JSON.stringify(config, null, 2).split('\n').join('\n    ')}

    // Fallback for missing config (safety net)
    if (typeof GAME_CONFIG === 'undefined') {
      console.error('GAME_CONFIG not defined - using defaults')
      window.GAME_CONFIG = ${JSON.stringify(config, null, 2).split('\n').join('\n      ')}
    }

    // Set document title from config
    document.title = GAME_CONFIG.gameTitle`
}

function generateGame(petName, configPath = null) {
  // Load or create config
  let config
  if (configPath) {
    const fullConfigPath = path.resolve(ROOT_DIR, configPath)
    if (!fs.existsSync(fullConfigPath)) {
      console.error(`Error: Config file not found: ${fullConfigPath}`)
      process.exit(1)
    }
    const configData = fs.readFileSync(fullConfigPath, 'utf8')
    config = JSON.parse(configData)
  } else {
    // Check if a config exists in configs/
    const defaultConfigPath = path.join(ROOT_DIR, 'configs', `${petName.toLowerCase()}.json`)
    if (fs.existsSync(defaultConfigPath)) {
      const configData = fs.readFileSync(defaultConfigPath, 'utf8')
      config = JSON.parse(configData)
      console.log(`Using config from: ${defaultConfigPath}`)
    } else {
      config = createDefaultConfig(petName)
      console.log('Using generated default config')
    }
  }

  // Load template
  const templatePath = path.join(ROOT_DIR, 'templates', 'game-template.html')
  if (!fs.existsSync(templatePath)) {
    console.error(`Error: Template not found: ${templatePath}`)
    process.exit(1)
  }
  const template = fs.readFileSync(templatePath, 'utf8')

  // Generate config script
  const configScript = generateConfigScript(config)

  // Replace placeholder with config
  const output = template.replace('/* GAME_CONFIG_PLACEHOLDER */', configScript)

  // Create output directory
  const outputDir = path.join(ROOT_DIR, 'games', config.petName)
  fs.mkdirSync(outputDir, { recursive: true })

  // Write output file
  const outputPath = path.join(outputDir, 'index.html')
  fs.writeFileSync(outputPath, output)

  console.log(`\n✅ Generated game for ${config.petDisplayName}`)
  console.log(`   Output: ${outputPath}`)
  console.log(`   Title: ${config.gameTitle}`)
  console.log(`\nTo test locally: open ${outputPath} in a browser`)
  console.log(`After deploy: https://sparkleclassic.com/${config.petName}/`)
}

// Parse command line arguments
const args = process.argv.slice(2)

if (args.length === 0) {
  console.log(`
Generate Game - Create personalized pet games

Usage:
  node scripts/generate-game.js <petName>
  node scripts/generate-game.js <petName> --config <configPath>

Examples:
  node scripts/generate-game.js bowie           # Uses configs/bowie.json or defaults
  node scripts/generate-game.js fluffy --config configs/fluffy.json

Output:
  games/<petName>/index.html
`)
  process.exit(0)
}

const petName = args[0]
let configPath = null

// Check for --config flag
const configFlagIndex = args.indexOf('--config')
if (configFlagIndex !== -1 && args[configFlagIndex + 1]) {
  configPath = args[configFlagIndex + 1]
}

generateGame(petName, configPath)
